# @see https://github.com/drevops/drupal_circleci
version: 2
aliases:
  # SSH deployment key fingerprint from CircleCI App -> Project -> Settings -> SSH Permissions.
  # Replace the value for your project.
  - &deploy_ssh_fingerprint "d1:d2:3b:87:e8:6c:c1:7c:d2:d7:65:43:30:7b:e6:6b"
  - &container_config
    working_directory: ~/project
    docker:
      - image: circleci/php:7.4-cli-browsers

job-build: &job-build
  steps:
    - checkout
    - run: .circleci/install-dependencies.sh
    - run: .circleci/build.sh
    - run: .circleci/lint.sh
    - run: .circleci/test.sh
    - run:
        command: .circleci/process-artifacts.sh
        when: always
    - store_test_results:
        path: /tmp/test_results
    - store_artifacts:
        path: /tmp/artifacts

jobs:
  build-php-8.1-legacy:
    <<: *container_config
    docker:
      - image: circleci/php:8.1-cli-browsers
    environment:
      DRUPAL_VERSION: 9.4.15
      DRUPAL_PROJECT_SHA: 9.4.15
    <<: *job-build

  deploy:
    <<: *container_config
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - run: DEPLOY_BRANCH=${CIRCLE_BRANCH} .circleci/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build-php-8.1-legacy:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-php-8.1-legacy
          filters:
            tags:
              only: /.*/
            branches:
              # 1.x, 2.x...
              only: /(?:[1-9]\.x)/
